name: Scribe evidence verify
description: Verify compliance policies against evidence to ensure the integrity of supply chain.
author: Mikey Strauss
outputs:
  OUTPUT_PATH:
    description: evidence output file path
    value: ""
inputs:
  target:
    description: Target object name format=[<image:tag>, <dir path>, <git url>] (Optional)
    required: true
  all-evidence:
    description: Run all evidence verification
  attest-config:
    description: Attestation config path
  attest-default:
    description: Attestation default config, options=[sigstore sigstore-github x509 x509-env kms pubkey]
  attestation:
    description: Attestation for target
  base-image:
    description: Base image for the target
  beautify:
    description: Enhance the output using ANSI and Unicode characters
  bom:
    description: Create target SBOM evidence
  bundle:
    description: Policy bundle uri/path (early-availability)
  bundle-auth:
    description: 'Bundle repository authentication info, [format: ''username:password'']'
  bundle-branch:
    description: Bundle branch in the repository
  bundle-commit:
    description: Bundle commit hash in the repository
  bundle-depth:
    description: Bundle clone depth
  bundle-tag:
    description: Bundle tag in the repository
  ca:
    description: x509 CA Chain path
  cert:
    description: x509 Cert path
  common-name:
    description: Default policy allowed common names
  crl:
    description: x509 CRL path
  crl-full-chain:
    description: Enable Full chain CRL verfication
  depth:
    description: Git clone depth
  disable-crl:
    description: Disable certificate revocation verificatoin
  email:
    description: Default policy allowed emails
  force:
    description: Force skip cache
  format:
    description: Policy Result Evidence format, options=[statement-sarif attest-sarif sarif ]
  git-auth:
    description: 'Git repository authentication info, [format: ''username:password'']'
  git-branch:
    description: Git branch in the repository
  git-commit:
    description: Git commit hash in the repository
  git-tag:
    description: Git tag in the repository
  initiative:
    description: Initiative configuration file path (early-availability)
  initiative-id:
    description: Initiative id
  initiative-name:
    description: Initiative name
  input-format:
    description: Input Evidence format, options=[attest-cyclonedx-json attest-slsa statement-slsa statement-cyclonedx-json statement-generic attest-generic ]
  key:
    description: x509 Private key path
  kms:
    description: Provide KMS key reference
  md:
    description: Output Initiative result markdown report file
  oci:
    description: Enable OCI store
  oci-repo:
    description: Select OCI custom attestation repo
  pass:
    description: Private key password
  payload:
    description: path of the decoded payload
  platform:
    description: Select target platform, examples=windows/armv6, arm64 ..)
  provenance:
    description: Create target SLSA Provenance evidence
  pubkey:
    description: Public key path
  public-key:
    description: Public key path
  rule:
    description: Rule configuration file path (early-availability)
  rule-args:
    description: Policy arguments
  rule-label:
    description: Run only rules with specified label
  skip-bundle:
    description: Skip bundle download
  skip-confirmation:
    description: Skip Sigstore Confirmation
  skip-report:
    description: Skip Policy report stage
  source:
    description: SLSA Git repository source for target
  source-asset-id:
    description: Source asset id for SLSA Git repository source
  source-asset-name:
    description: Source asset name for SLSA Git repository source
  source-asset-platform:
    description: Source asset platform for SLSA Git repository source
  uri:
    description: Default policy allowed uris
  cache-enable:
    description: Enable local cache
  config:
    description: Configuration file path
  deliverable:
    description: Mark as deliverable, options=[true, false]
  env:
    description: Environment keys to include in evidence
  gate-name:
    description: Policy Gate name
  gate-type:
    description: Policy Gate type
  input:
    description: Input Evidence target, format (\<parser>:\<file> or \<scheme>:\<name>:\<tag>)
  label:
    description: Add Custom labels
  level:
    description: Log depth level, options=[panic fatal error warning info debug trace]
  log-context:
    description: Attach context to all logs
  log-file:
    description: Output log to file
  output-directory:
    description: Output directory path
    default: ./scribe/valint
  output-file:
    description: Output file name
  pipeline-name:
    description: Pipeline name
  predicate-type:
    description: Custom Predicate type (generic evidence format)
  product-key:
    description: Product Key
  product-version:
    description: Product Version
  scribe-client-id:
    description: Scribe Client ID (deprecated)
  scribe-client-secret:
    description: Scribe Client Token
  scribe-disable:
    description: Disable scribe client
  scribe-enable:
    description: Enable scribe client (deprecated)
  scribe-url:
    description: Scribe API Url
  structured:
    description: Enable structured logger
  timeout:
    description: Timeout duration
  verbose:
    description: Log verbosity level [-v,--verbose=1] = info, [-vv,--verbose=2] = debug
runs:
  using: docker
  image: docker://scribesecurity/valint:v2.0.1
  args:
    - verify
    - ${{ inputs.target }}
    - ${{ inputs.all-evidence && '--all-evidence=' }}${{ inputs.all-evidence }}
    - ${{ inputs.attest-config && '--attest.config=' }}${{ inputs.attest-config }}
    - ${{ inputs.attest-default && '--attest.default=' }}${{ inputs.attest-default }}
    - ${{ inputs.attestation && '--attestation=' }}${{ inputs.attestation }}
    - ${{ inputs.base-image && '--base-image=' }}${{ inputs.base-image }}
    - ${{ inputs.beautify && '--beautify=' }}${{ inputs.beautify }}
    - ${{ inputs.bom && '--bom=' }}${{ inputs.bom }}
    - ${{ inputs.bundle && '--bundle=' }}${{ inputs.bundle }}
    - ${{ inputs.bundle-auth && '--bundle-auth=' }}${{ inputs.bundle-auth }}
    - ${{ inputs.bundle-branch && '--bundle-branch=' }}${{ inputs.bundle-branch }}
    - ${{ inputs.bundle-commit && '--bundle-commit=' }}${{ inputs.bundle-commit }}
    - ${{ inputs.bundle-depth && '--bundle-depth=' }}${{ inputs.bundle-depth }}
    - ${{ inputs.bundle-tag && '--bundle-tag=' }}${{ inputs.bundle-tag }}
    - ${{ inputs.ca && '--ca=' }}${{ inputs.ca }}
    - ${{ inputs.cert && '--cert=' }}${{ inputs.cert }}
    - ${{ inputs.common-name && '--common-name=' }}${{ inputs.common-name }}
    - ${{ inputs.crl && '--crl=' }}${{ inputs.crl }}
    - ${{ inputs.crl-full-chain && '--crl-full-chain=' }}${{ inputs.crl-full-chain }}
    - ${{ inputs.depth && '--depth=' }}${{ inputs.depth }}
    - ${{ inputs.disable-crl && '--disable-crl=' }}${{ inputs.disable-crl }}
    - ${{ inputs.email && '--email=' }}${{ inputs.email }}
    - ${{ inputs.force && '--force=' }}${{ inputs.force }}
    - ${{ inputs.format && '--format=' }}${{ inputs.format }}
    - ${{ inputs.git-auth && '--git-auth=' }}${{ inputs.git-auth }}
    - ${{ inputs.git-branch && '--git-branch=' }}${{ inputs.git-branch }}
    - ${{ inputs.git-commit && '--git-commit=' }}${{ inputs.git-commit }}
    - ${{ inputs.git-tag && '--git-tag=' }}${{ inputs.git-tag }}
    - ${{ inputs.initiative && '--initiative=' }}${{ inputs.initiative }}
    - ${{ inputs.initiative-id && '--initiative-id=' }}${{ inputs.initiative-id }}
    - ${{ inputs.initiative-name && '--initiative-name=' }}${{ inputs.initiative-name }}
    - ${{ inputs.input-format && '--input-format=' }}${{ inputs.input-format }}
    - ${{ inputs.key && '--key=' }}${{ inputs.key }}
    - ${{ inputs.kms && '--kms=' }}${{ inputs.kms }}
    - ${{ inputs.md && '--md=' }}${{ inputs.md }}
    - ${{ inputs.oci && '--oci=' }}${{ inputs.oci }}
    - ${{ inputs.oci-repo && '--oci-repo=' }}${{ inputs.oci-repo }}
    - ${{ inputs.pass && '--pass=' }}${{ inputs.pass }}
    - ${{ inputs.payload && '--payload=' }}${{ inputs.payload }}
    - ${{ inputs.platform && '--platform=' }}${{ inputs.platform }}
    - ${{ inputs.provenance && '--provenance=' }}${{ inputs.provenance }}
    - ${{ inputs.pubkey && '--pubkey=' }}${{ inputs.pubkey }}
    - ${{ inputs.public-key && '--public-key=' }}${{ inputs.public-key }}
    - ${{ inputs.rule && '--rule=' }}${{ inputs.rule }}
    - ${{ inputs.rule-args && '--rule-args=' }}${{ inputs.rule-args }}
    - ${{ inputs.rule-label && '--rule-label=' }}${{ inputs.rule-label }}
    - ${{ inputs.skip-bundle && '--skip-bundle=' }}${{ inputs.skip-bundle }}
    - ${{ inputs.skip-confirmation && '--skip-confirmation=' }}${{ inputs.skip-confirmation }}
    - ${{ inputs.skip-report && '--skip-report=' }}${{ inputs.skip-report }}
    - ${{ inputs.source && '--source=' }}${{ inputs.source }}
    - ${{ inputs.source-asset-id && '--source-asset-id=' }}${{ inputs.source-asset-id }}
    - ${{ inputs.source-asset-name && '--source-asset-name=' }}${{ inputs.source-asset-name }}
    - ${{ inputs.source-asset-platform && '--source-asset-platform=' }}${{ inputs.source-asset-platform }}
    - ${{ inputs.uri && '--uri=' }}${{ inputs.uri }}
    - ${{ inputs.cache-enable && '--cache-enable=' }}${{ inputs.cache-enable }}
    - ${{ inputs.config && '--config=' }}${{ inputs.config }}
    - --context-type=github
    - ${{ inputs.deliverable && '--deliverable=' }}${{ inputs.deliverable }}
    - ${{ inputs.env && '--env=' }}${{ inputs.env }}
    - ${{ inputs.gate-name && '--gate-name=' }}${{ inputs.gate-name }}
    - ${{ inputs.gate-type && '--gate-type=' }}${{ inputs.gate-type }}
    - ${{ inputs.input && '--input=' }}${{ inputs.input }}
    - ${{ inputs.label && '--label=' }}${{ inputs.label }}
    - ${{ inputs.level && '--level=' }}${{ inputs.level }}
    - ${{ inputs.log-context && '--log-context=' }}${{ inputs.log-context }}
    - ${{ inputs.log-file && '--log-file=' }}${{ inputs.log-file }}
    - ${{ inputs.output-directory && '--output-directory=' }}${{ inputs.output-directory }}
    - ${{ inputs.output-file && '--output-file=' }}${{ inputs.output-file }}
    - ${{ inputs.pipeline-name && '--pipeline-name=' }}${{ inputs.pipeline-name }}
    - ${{ inputs.predicate-type && '--predicate-type=' }}${{ inputs.predicate-type }}
    - ${{ inputs.product-key && '--product-key=' }}${{ inputs.product-key }}
    - ${{ inputs.product-version && '--product-version=' }}${{ inputs.product-version }}
    - ${{ inputs.scribe-client-id && '--scribe.client-id=' }}${{ inputs.scribe-client-id }}
    - ${{ inputs.scribe-client-secret && '--scribe.client-secret=' }}${{ inputs.scribe-client-secret }}
    - ${{ inputs.scribe-disable && '--scribe.disable=' }}${{ inputs.scribe-disable }}
    - ${{ inputs.scribe-enable && '--scribe.enable=' }}${{ inputs.scribe-enable }}
    - ${{ inputs.scribe-url && '--scribe.url=' }}${{ inputs.scribe-url }}
    - ${{ inputs.structured && '--structured=' }}${{ inputs.structured }}
    - ${{ inputs.timeout && '--timeout=' }}${{ inputs.timeout }}
    - ${{ inputs.verbose && '--verbose=' }}${{ inputs.verbose }}
branding:
  icon: shield
  color: green
