name: 'valint: verify'
description: 'Verify a Signed Software Bill Of Materials (SBOM) from container images and filesystems'
author: Mikey Strauss
inputs:
  type:
    description: 'Target source type options=[docker,docker-archive, oci-archive, dir, registry]'
    default: registry
  target:
    description: 'Target object name format=[<image:tag>, <dir_path>]'
    required: true
  verbose:
    description: 'Increase verbosity (-v = info, -vv = debug)'
    default: 1
  config:
    description: 'Application config file'
  input-format:
    description: 'Sbom input formatter, options=[attest-cyclonedx-json attest-slsa]  (default "attest-cyclonedx-json")'
    default: attest-cyclonedx-json
  output-directory:
    description: 'report output directory'
    default: ./scribe/valint
  output-file:
    description: 'Output result to file'
  filter-regex:
    description: 'Filter out files by regex'
    default: .*\.pyc,\.git/.*
  attest-config:
    description: 'Attestation config map'
  attest-name:
    description: 'Attestation config name (default "valint")'
  attest-default:
    description: 'Attestation default config, options=[sigstore sigstore-github x509]'
    default: sigstore-github
  attestation:
    description: 'Attestation for target'
  oci: 
    description: 'Enable OCI store'
    default: false
  oci-repo:
    description: 'Select OCI custom attestation repo'

runs:
  using: docker
  image: docker://scribesecuriy.jfrog.io/scribe-docker-public-local/valint:dev-latest 
  args:
    - verify
    - ${{ inputs.type }}:${{ inputs.target }}
    - --verbose=${{ inputs.verbose }}
    - ${{ inputs.config && '--config=' }}${{ inputs.config }}
    - ${{ inputs.output-directory && '--output-directory=' }}${{ inputs.output-directory }}
    # - --format=${{ inputs.format }}
    - --input-format=${{ inputs.input-format }}
    - --context-type=github
    - ${{ inputs.filter-regex && '--filter-regex=' }}${{ inputs.filter-regex }}
    - ${{ inputs.attest-config && '--attest.config=' }}${{ inputs.attest-config }}
    - ${{ inputs.attest-name && '--attest.name=' }}${{ inputs.attest-name }}
    - ${{ inputs.attest-default && '--attest.default=' }}${{ inputs.attest-default }}
    - ${{ inputs.output-file && '--output-file=' }}${{ inputs.output-file }}
    - ${{ inputs.attestation && '--attestation=' }}${{ inputs.attestation }}
    - ${{ inputs.oci && '--oci=' }}${{ inputs.oci }}
    - ${{ inputs.oci-repo && '--oci-repo=' }}${{ inputs.oci-repo }}

branding:
  icon: shield
  color: green
